using MazeGame.MazeGame.Application.Commands;
using MazeGame.MazeGame.Core.Interactables;
using MazeGame.MazeGame.Presentation;

namespace MazeGame.MazeGame.Core.Misc;

public class GameInit
{
    private int width;
    private int height;
    private Dictionary<(int x, int y), Room> roomPositions;

    public GameInit(int width, int height)
    {
        roomPositions = new();
        this.width = width;
        this.height = height;
    }

    public Room? tryGetRoom(int x, int y)
    {
        roomPositions.TryGetValue((x, y), out Room? room);
        return room;
    }

    public void addEntity((int, int) roomPos, Entity entity)
    {
        Room? room = tryGetRoom(roomPos.Item1, roomPos.Item2);
        room?.setEntity(entity);
    }

    public Room roomGen(string sequence)
    {
        int count = 1;
        Room spawnRoom = new Room("spawn", width, height);
        roomPositions.Add((0, 0), spawnRoom);
        Room travRoom = spawnRoom;
        (int, int) lastPos = roomPositions.Last().Key;
        foreach (char letter in sequence)
        {
            Direction dir = charToDirection(letter);
            (int, int) tempRoomPos = Util.addTuples(lastPos, Util.directionToPosition(dir));
            roomPositions.TryGetValue(tempRoomPos, out Room? tempRoom);
            if (tempRoom == null)
            {
                tempRoom = new Room("" + count, width, height);
                roomPositions.Add(tempRoomPos, tempRoom);
            }
            else
            {
                lastPos = tempRoomPos;
                travRoom = tempRoom;
            }

            neighborLink(travRoom, lastPos, roomPositions);
            travRoom = tempRoom;
            lastPos = tempRoomPos;
            count++;
        }

        return spawnRoom;
    }

    private void neighborLink(Room room, (int, int) pos, Dictionary<(int x, int y), Room> roomPositions)
    {
        foreach (Direction dir in Enum.GetValues<Direction>())
        {
            (int, int) tup = Util.addTuples(Util.directionToPosition(dir), pos);
            if (roomPositions.ContainsKey(tup))
            {
                doorLink(room, roomPositions[tup], dir);
            }
        }
    }

    private void doorLink(Room thisRoom, Room otherRoom, Direction direction)
    {
        thisRoom.linkRoom(direction, otherRoom);
        int normalX, normalY;
        (normalX, normalY) = getDoorPosition(direction, thisRoom.playAreaWidth(), thisRoom.playAreaHeight());
        int mirrorX = Util.clamp(normalX, otherRoom.playAreaWidth());
        int mirrorY = Util.clamp(normalY, otherRoom.playAreaHeight());
        Direction mirror = Util.mirrorDirection(direction);
        if (direction == Direction.right || direction == Direction.down)
        {
            int tx = normalX, ty = normalY;
            normalX = mirrorX;
            normalY = mirrorY;
            mirrorX = tx;
            mirrorY = ty;
        }

        thisRoom.setEntity(new Entity($"door_{direction}", normalX, normalY, new Open(),
            new Renders(new Render("☐", ConsoleColor.Green))));
        otherRoom.setEntity(new Entity($"door_{mirror}", mirrorX, mirrorY, new Open(),
            new Renders(new Render("☐", ConsoleColor.Green))));
    }

    public Entity getAutoGeneratedDoor(Room room, Direction? direction = null)
    {
        List<Entity> doors = room.getEntityList().FindAll(ent => ent.name.Contains("door")).Select(ent => ent).ToList();
        return direction == null ? doors.First() : doors.Find(door => door.name.Contains(direction.ToString()));
    }

    private (int x, int y) getDoorPosition(Direction direction, int x, int y)
    {
        double multX = 1;
        double multY = 1;
        if (direction == Direction.up || direction == Direction.down)
        {
            multX = 0.5;
            multY = 0;
        }
        else if (direction == Direction.left || direction == Direction.right)
        {
            multX = 0;
            multY = 0.5;
        }

        return ((int)Math.Ceiling(x * multX), (int)Math.Ceiling(y * multY));
    }

    private Direction charToDirection(char letter)
    {
        letter = letter.ToString().ToUpper()[0];
        switch (letter)
        {
            case 'L':
                return Direction.left;
            case 'R':
                return Direction.right;
            case 'U':
                return Direction.up;
            case 'D':
                return Direction.down;
        }

        return default;
    }
}