using MazeGame.MazeGame.Application.Commands;
using MazeGame.MazeGame.Application.Enums;
using MazeGame.MazeGame.Core.Enums;
using MazeGame.MazeGame.Core.Interactables;
using MazeGame.MazeGame.Core.Module;
using MazeGame.MazeGame.Presentation;

namespace MazeGame.MazeGame.Core.LoadScene;

public class MapMaker
{
    private Dictionary<IntVector2, Node> nodeTable;
    private int width;
    private int height;

    public MapMaker(int width, int height)
    {
        nodeTable = new Dictionary<IntVector2, Node>();
        this.width = width;
        this.height = height;
    }

    public Node? getNode(IntVector2 pos) => nodeTable.GetValueOrDefault(pos);
    public Room? getRoom(IntVector2 pos) => getNode(pos)?.room;

    public Node generateMap(string sequence)
    {
        int count = 1;
        Node spawn = new Node(new Room("spawn", width, height));
        nodeTable[new IntVector2(0, 0)] = spawn;
        Node traverse = spawn;
        IntVector2 lastPosition = nodeTable.Last().Key;
        foreach (char letter in sequence)
        {
            Directions directions = charToDirection(letter);
            IntVector2 tempRoomPosition = lastPosition + Util.directionVector[directions];
            nodeTable.TryGetValue(tempRoomPosition, out Node? temp);
            if (temp == null)
            {
                temp = new Node(new Room("" + count, width, height));
                nodeTable[tempRoomPosition] = temp;
            }
            else
            {
                lastPosition = tempRoomPosition;
                traverse = temp;
            }

            neighborLink(traverse, lastPosition);
            traverse = temp;
            lastPosition = tempRoomPosition;
            count++;
        }

        return spawn;
    }

    private void neighborLink(Node node, IntVector2 position)
    {
        foreach (Directions direction in Enum.GetValues<Directions>())
        {
            IntVector2 addedPosition = Util.directionVector[direction] + position;
            if (nodeTable.ContainsKey(addedPosition))
            {
                doorLink(node, nodeTable[addedPosition], direction);
            }
        }
    }

    private void doorLink(Node self, Node target, Directions direction)
    {
        self.link(direction, target);
        IntVector2 normalPos = getDoorPosition(direction, new IntVector2(self.room.getPlayareaWidth(), self.room.getPlayareaHeight()));
        IntVector2 mirrorPos = new IntVector2
        {
            X = Util.wrapAround(normalPos.X, target.room.getPlayareaWidth()),
            Y = Util.wrapAround(normalPos.Y, target.room.getPlayareaHeight())
        };

        Directions mirror = Util.mirrorDirection[direction];
        if (direction == Directions.RIGHT || direction == Directions.DOWN)
        {
            IntVector2 tempPos = new(normalPos);
            normalPos = mirrorPos;
            mirrorPos = tempPos;
        }

        self.room.setEntity(new Entity($"door_{Util.enumToString(direction)}", normalPos,
            [new Open(), new Renders(new Render("☐", ConsoleColor.Green))], [Tags.Doorway]));

        target.room.setEntity(new Entity($"door_{Util.enumToString(mirror)}", mirrorPos,
            [new Open(), new Renders(new Render("☐", ConsoleColor.Green))], [Tags.Doorway]));
    }

    public Entity getAutoGeneratedDoor(Room room, Directions? direction = null)
    {
        List<Entity> doors = room.getEntityList().FindAll(entity => entity.tags.Contains(Tags.Doorway)).Select(entity => entity).ToList();

        return direction == null ? doors.First() : doors.Find(door => door.name.Contains(Util.enumToString(direction))) ?? doors.First();
    }

    private IntVector2 getDoorPosition(Directions directions, IntVector2 pos)
    {
        double multX = 1;
        double multY = 1;
        if (directions == Directions.UP || directions == Directions.DOWN)
        {
            multX = 0.5;
            multY = 0;
        }
        else if (directions == Directions.LEFT || directions == Directions.RIGHT)
        {
            multX = 0;
            multY = 0.5;
        }

        return new IntVector2((int)Math.Ceiling(pos.X * multX), (int)Math.Ceiling(pos.Y * multY));
    }

    private Directions charToDirection(char letter)
    {
        letter = letter.ToString().ToUpper().First();
        switch (letter)
        {
            case 'L':
                return Directions.LEFT;
            case 'R':
                return Directions.RIGHT;
            case 'U':
                return Directions.UP;
            case 'D':
                return Directions.DOWN;
        }

        return default;
    }
}